 networks:
      - internal-dev
      - external-host

  adminer-dev:
    image: 'adminer:4.8.1-standalone'
    container_name: adminer-dev
    ports:
      - '8080:8080'
    depends_on:
      - npb-db-dev
    networks:
      - internal-dev
      - external-host

volumes:
  npb-app-dev-node_modules:
  npb-app-dev-next:

networks:
  internal-dev:
    external: false
  external-host:
    external: true